# Copyright (c) 2024 The OneD Authors
# See LICENSE file.

module(
    name = "oned",
    version = "head",
    compatibility_level = 1,
)
bazel_dep(name = "googletest", version = "1.15.0")
bazel_dep(name = "google_benchmark", version = "1.8.5")
bazel_dep(name = "tinyxml2", version = "10.0.0")
bazel_dep(name = "nlohmann_json", version = "3.11.3.bcr.1")